SPACE = '🌫'
ROBOT = '🚂'
OBSTA = 'X'
CAJA =  "📦"
DESTINO = "🏴‍☠️"

tablero = (
    [SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE],
    [SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE],
    [SPACE, SPACE, SPACE, SPACE, CAJA, SPACE, SPACE],
    [SPACE, SPACE, SPACE, ROBOT, SPACE, SPACE, SPACE],
    [SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE],
    [SPACE,CAJA, SPACE, SPACE, SPACE, SPACE, SPACE],
    [SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE],
    [SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, DESTINO],
)
